### PR TITLE
Possible solution to issue #77

### LINKED ISSUE #77: Add default implementation for the instances processor
Hi @othub can you please add a default implementation for the instances processor trait?

https://github.com/weso/hercules-ontology/blob/ea53344cd221c66a11f9a36725885dbe927562f1/ci/src/main/scala/es/weso/asio/ci/InstancesProcessor.scala#L1-L24

Its behaviour is almost the same as the one of the `OntologyProcessor.scala`

If yes please, fork, **create a new branch for the feature** (it's really important in order to be able to test it locally by reviewers) and initiate a PR to this [branch](https://github.com/weso/hercules-ontology/tree/ci-dev). An remember to add tests to the feature that you add please.

_Thanks._

### PR DESCRIPTION
**Pull request by othub**

### CODE REVIEW

**Comment by othub** [comment]
Hold on please, there was an error in git push, and files are not updated

**Comment by alejgh** [comment]
> Hold on please, there was an error in git push, and files are not updated

Yep, GitHub was having some problems in the last hours, I have also lost information about some commits in other repos... :weary:

**Comment by othub** [comment]
> > Hold on please, there was an error in git push, and files are not updated
> 
> Yep, GitHub was having some problems in the last hours, I have also lost information about some commits in other repos... 😩

We certainly picked the right timing to make changes  🙃

**Comment by thewillyhuman** [comment]
Hi @othub when I execute your tests locally i got this:

```scala

Exception: Unexpected end of file
Base:None, format: Turtle (mimeTypes=text/turtle, application/x-turtle; ext=ttl)
PREFIX :       <http://example.org/>PREFIX schema: <http://schema.org/>PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>PREFIX foaf:   <http://xmlns.com/foaf/0.1/>:alice schema:name           "Alice" ;            # %* \Passes{:User} *)       schema:gender         schema:Female ;       schema:knows          :bob .:bob   schema:gender         schema:Male ;        # %* \Passes{:User} *)       schema:name           "Robert";       schema:birthDate      "1980-03-10"^^xsd:date .:carol schema:name           "Carol" ;            # %* \Passes{:User} *)       schema:gender         "unspecified" ;       foaf:name             "Carol" .:dave  schema:name           "Dave";         # %* \Fails{:User} *)       schema:gender         "XYY";          #       schema:birthDate      1980 .          # %* 1980 is not an xsd:date *):emily schema:name "Emily", "Emilee" ;       # %* \Fails{:User} *)       schema:gender         schema:Female . # %* too many schema:names *):frank foaf:name             "Frank" ;       # %* \Fails{:User} *)       schema:gender:        schema:Male .   # %* missing schema:name *):grace schema:name           "Grace" ;       # %* \Fails{:User} *)       schema:gender         schema:Male ;   #       schema:knows          _:x .           # %* \_:x is not an IRI *):harold schema:name         "Harold" ;    # %* \Fails{:User} *)        schema:gender       schema:Male ;        schema:knows        :grace .      
es.weso.utils.IOException: Exception: Unexpected end of file
Base:None, format: Turtle (mimeTypes=text/turtle, application/x-turtle; ext=ttl)
PREFIX :       <http://example.org/>PREFIX schema: <http://schema.org/>PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>PREFIX foaf:   <http://xmlns.com/foaf/0.1/>:alice schema:name           "Alice" ;            # %* \Passes{:User} *)       schema:gender         schema:Female ;       schema:knows          :bob .:bob   schema:gender         schema:Male ;        # %* \Passes{:User} *)       schema:name           "Robert";       schema:birthDate      "1980-03-10"^^xsd:date .:carol schema:name           "Carol" ;            # %* \Passes{:User} *)       schema:gender         "unspecified" ;       foaf:name             "Carol" .:dave  schema:name           "Dave";         # %* \Fails{:User} *)       schema:gender         "XYY";          #       schema:birthDate      1980 .          # %* 1980 is not an xsd:date *):emily schema:name "Emily", "Emilee" ;       # %* \Fails{:User} *)       schema:gender         schema:Female . # %* too many schema:names *):frank foaf:name             "Frank" ;       # %* \Fails{:User} *)       schema:gender:        schema:Male .   # %* missing schema:name *):grace schema:name           "Grace" ;       # %* \Fails{:User} *)       schema:gender         schema:Male ;   #       schema:knows          _:x .           # %* \_:x is not an IRI *):harold schema:name         "Harold" ;    # %* \Fails{:User} *)        schema:gender       schema:Male ;        schema:knows        :grace .      
	at es.weso.utils.IOException$.fromString(IOUtils.scala:15)
	at es.weso.utils.IOUtils$.$anonfun$fromES$1(IOUtils.scala:22)
	at cats.syntax.EitherOps$.leftMap$extension(either.scala:151)
	at es.weso.utils.IOUtils$.fromES(IOUtils.scala:22)
	at es.weso.rdf.rdf4j.RDFAsRDF4jModel.fromString(RDFAsRDF4jModel.scala:41)
	at es.weso.rdf.rdf4j.RDFAsRDF4jModel$.$anonfun$fromChars$1(RDFAsRDF4jModel.scala:333)
	at cats.effect.internals.IORunLoop$.liftedTree3$1(IORunLoop.scala:238)
	at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:238)
	at cats.effect.IO.unsafeRunTimed(IO.scala:321)
	at cats.effect.IO.unsafeRunSync(IO.scala:240)
	at es.weso.asio.ci.utils.MergeRDF4JUtil.mergeRDF4JModels(MergeRDF4JUtil.scala:39)
	at es.weso.asio.ci.DefaultInstancesProcessor.getInstancesModel(DefaultInstancesProcessor.scala:27)
	at es.weso.asio.ci.DefaultInstanceProcessorTest.$anonfun$new$5(DefaultInstanceProcessorTest.scala:51)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:189)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.funsuite.AnyFunSuite.withFixture(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:187)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:199)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:199)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:181)
	at es.weso.asio.ci.DefaultInstanceProcessorTest.org$scalatest$BeforeAndAfter$$super$runTest(DefaultInstanceProcessorTest.scala:9)
	at org.scalatest.BeforeAndAfter.runTest(BeforeAndAfter.scala:213)
	at org.scalatest.BeforeAndAfter.runTest$(BeforeAndAfter.scala:203)
	at es.weso.asio.ci.DefaultInstanceProcessorTest.runTest(DefaultInstanceProcessorTest.scala:9)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:232)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:232)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:231)
	at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1562)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:236)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:236)
	at org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:235)
	at es.weso.asio.ci.DefaultInstanceProcessorTest.org$scalatest$BeforeAndAfter$$super$run(DefaultInstanceProcessorTest.scala:9)
	at org.scalatest.BeforeAndAfter.run(BeforeAndAfter.scala:273)
	at org.scalatest.BeforeAndAfter.run$(BeforeAndAfter.scala:271)
	at es.weso.asio.ci.DefaultInstanceProcessorTest.run(DefaultInstanceProcessorTest.scala:9)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1320)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1314)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1314)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)

```

That comes from this test:

```scala

test("Correct instances directory and only one existing ttl file in said directory") {
    val model = instanceProcessor.getInstancesModel
    //asserting that there was no exception and returning an empty model
    assert(model.isRight)
    inside(model) { case Right(rightModel) =>
      //merging complete
      assert(rightModel.serialize().unsafeRunSync().contains("alice"))
      assert(rightModel.serialize().unsafeRunSync().contains("bob"))
      assert(rightModel.serialize().unsafeRunSync().contains("carol"))
      assert(rightModel.serialize().unsafeRunSync().contains("dave"))
      assert(rightModel.serialize().unsafeRunSync().contains("emily"))
      assert(rightModel.serialize().unsafeRunSync().contains("frank"))
      assert(rightModel.serialize().unsafeRunSync().contains("grace"))
    }
  }

```

And more precisely from this line:

```scala
val model = instanceProcessor.getInstancesModel
```

Does this also happen to you?

**Comment by othub** [comment]
@thewilly it seems there is something wrong in the content of example-1.ttl because when i changed the content of it for example to some of the lines from asia-core, the test worked (well with different asserts obviously)

**Comment by thewillyhuman** [comment]
> 
> 
> @thewilly it seems there is something wrong in the content of example-1.ttl because when i changed the content of it for example to some of the lines from asia-core, the test worked (well with different asserts obviously)

@othub you can modify that file content without problem, or even create your own file. Just keep in mind that if you modify it maybe another test stops working.

**Comment by thewillyhuman** [comment]
I'm working on travis conf before review.

**Pull request merged**
