### PR TITLE
[HOP-0122] Added some projects and funding programmes

### PR DESCRIPTION
**Pull request by sofimrtn**
When talking about european projects, should I just put asio:EuropeanProject or should I use both? At the moment I just used asio:Project because I wasn't sure. I will change it accordingly if needed.

### CODE REVIEW

**Comment by alejgh** [comment]
We should try to use EuropeanProject/NationalProject/RegionalProject whenever possible, since this is needed for many of the competency questions.

**Comment by alejgh** [comment]
Everything looks good to me.

@spitxa do you know if we have ready the property to link projects and Research Institutes?

I would like to have projects and research institutes linked before merging this PR.

**Comment by spitxa** [comment]
i'm hesitating about using _asio:hasResearchLine_ as symmetric or using _asio:hasResearchField_ to keep it differenciated.

**Comment by alejgh** [comment]
I prefer asio:hasResearchField since it would make queries a bit easier, but I have no problem if using hasResearchLine makes more sense from an ontological perspective.

**Comment by alejgh** [comment]
I think we need to have a way in the ontology to represent International projects like this one: https://www.cimne.com/sgp/rtd/Project.aspx?id=725

@spitxa what do you think? Or maybe these projects that are not European, National nor Regional do not need to be represented in the ontology?

**Review by alejgh — APPROVED** [review]
I have added everything to our wikibase instance, we can merge this PR.

**Comment by spitxa** [comment]
added new class asio:InternationalProject to deal with consortium projects featuring partners other than from the EU.

**Pull request merged**
